### ISSUE TITLE
[TASK] 데이터 베이스 생성 및 확인

### ISSUE THREAD

**Issue by tyufjvbn2** [codestates/challengers-server#26]
## TODO : 
- [ ] 1단계 : 로컬의 my sql에 데이터 베이스 생성
- [ ] 2단계 : 데이터 베이스내의 구성(테이블과 자료형)을 문서로 정리
- [ ] 3단계 : 정리된 문서를 다른 팀원에게 공유

#### 필수사항 : 
데이터 베이스에 접근할 때 환경변수 사용(.env)
